### PR TITLE
Allow to chnage stream metadata

### PR DESCRIPTION
**Pull request by hipek**
This change is [Reviewable](https://reviewable.io/reviews/nowthisnews/http_eventstore/7)

### CODE REVIEW

**Comment by ImmaculatePine** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[lib/http_eventstore/api/client.rb, line 16 at r1](https://reviewable.io:443/reviews/nowthisnews/http_eventstore/7#-L3CdYfPeMUkHxw-AOZu:-L3CdYfPeMUkHxw-AOZv:b-j3n1g7) ([raw file](https://github.com/nowthisnews/http_eventstore/blob/b8b0a414fd655e476d1616c5c03b0c58c9a54bd1/lib/http_eventstore/api/client.rb#L16)):*
> ```Ruby
>       end
> 
>       def update_stream_metadata(stream_name, event_id:, data: {})
> ```

Is there a way to create stream with required metadata? Or the only option is to create a generic stream and update its metadata in a separate request?

---

*[lib/http_eventstore/api/client.rb, line 17 at r1](https://reviewable.io:443/reviews/nowthisnews/http_eventstore/7#-L3Cdk4yEbNJphzles5V:-L3Cdk4yEbNJphzles5W:b-2fde2c) ([raw file](https://github.com/nowthisnews/http_eventstore/blob/b8b0a414fd655e476d1616c5c03b0c58c9a54bd1/lib/http_eventstore/api/client.rb#L17)):*
> ```Ruby
> 
>       def update_stream_metadata(stream_name, event_id:, data: {})
>         headers = { "Content-Type" => "application/json", "ES-EventId" => event_id }
> ```

Just curious: event_id - what event is that?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/nowthisnews/http_eventstore/7)*

**Comment by hipek** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[lib/http_eventstore/api/client.rb, line 16 at r1](https://reviewable.io:443/reviews/nowthisnews/http_eventstore/7#-L3CdYfPeMUkHxw-AOZu:-L3Cedoi-20ByDoWcyM4:b-myoiuc) ([raw file](https://github.com/nowthisnews/http_eventstore/blob/b8b0a414fd655e476d1616c5c03b0c58c9a54bd1/lib/http_eventstore/api/client.rb#L16)):*
<details><summary><i>Previously, ImmaculatePine (Alexander Borovykh) wrote…</i></summary><blockquote>

Is there a way to create stream with required metadata? Or the only option is to create a generic stream and update its metadata in a separate request?
</blockquote></details>

I wasn't able to find that information. But I think this is not a problem. You can create new stream by ONLY updating metadata. If stream doesn't exists metadata request will create it so we will have an empty stream with  correct metadata.

---

*[lib/http_eventstore/api/client.rb, line 17 at r1](https://reviewable.io:443/reviews/nowthisnews/http_eventstore/7#-L3Cdk4yEbNJphzles5V:-L3Cf2pQA4plaQZt_qIC:bxubp6m) ([raw file](https://github.com/nowthisnews/http_eventstore/blob/b8b0a414fd655e476d1616c5c03b0c58c9a54bd1/lib/http_eventstore/api/client.rb#L17)):*
<details><summary><i>Previously, ImmaculatePine (Alexander Borovykh) wrote…</i></summary><blockquote>

Just curious: event_id - what event is that?
</blockquote></details>

It's an EventStore :) All changes in ES are saved as events. So basically this event_id is for event that will represent changes in metadata :) I wasn't able to create metadata without providing event_id header...

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/nowthisnews/http_eventstore/7)*

**Comment by ImmaculatePine** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[lib/http_eventstore/api/client.rb, line 17 at r1](https://reviewable.io:443/reviews/nowthisnews/http_eventstore/7#-L3Cdk4yEbNJphzles5V:-L3CfwbVIXesP4_8QIeG:bcr5s2o) ([raw file](https://github.com/nowthisnews/http_eventstore/blob/b8b0a414fd655e476d1616c5c03b0c58c9a54bd1/lib/http_eventstore/api/client.rb#L17)):*
<details><summary><i>Previously, hipek (Jacek Hiszpanski) wrote…</i></summary><blockquote>

It's an EventStore :) All changes in ES are saved as events. So basically this event_id is for event that will represent changes in metadata :) I wasn't able to create metadata without providing event_id header...
</blockquote></details>

Got it, thanks!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/nowthisnews/http_eventstore/7#-:-L3CfywQUH5YgMciCRec:bnfp4nl)*

**Comment by ImmaculatePine** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/nowthisnews/http_eventstore/7)*

**Pull request merged**
