### PR TITLE
Change order of returned events in read_events_forward

### PR DESCRIPTION
**Pull request by hipek**
This change is [Reviewable](https://reviewable.io/reviews/nowthisnews/http_eventstore/3)

### CODE REVIEW

**Comment by akarmes** [comment]
:lgtm:
But that strange, that according to test it was consciously returning evens in reverse order. 

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/nowthisnews/http_eventstore/3#-:-KYIz_wH2MIpoRUq6UbA:b-pdm9po)*

**Comment by akarmes** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/nowthisnews/http_eventstore/3)*

**Comment by hipek** [comment]
Yes, we are aware of that but method read_all_events_forward already work like that - from oldest to newest. I just made it consistent.

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/nowthisnews/http_eventstore/3#-:-KYIzwt23fW_4NVgJLCJ:b-7wou2r)*

**Comment by swiercz** [comment]
:lgtm:

---

Reviewed 2 of 3 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/nowthisnews/http_eventstore/3#-:-KYJ-lX26bsxIGl7e5j4:bnfp4nl)*

**Comment by swiercz** [comment]
Reviewed 1 of 3 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/nowthisnews/http_eventstore/3)*

**Comment by bart84ek** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/nowthisnews/http_eventstore/3#-:-KYJ-xsZAc35g1tfU9ZD:bnfp4nl)*

**Pull request merged**
