### PR TITLE
Http adapter

### PR DESCRIPTION
**Pull request by hipek**
This change is [Reviewable](https://reviewable.io/reviews/nowthisnews/http_eventstore/2)

### CODE REVIEW

**Comment by rybex** [comment]
*[lib/http_eventstore/api/client.rb, line 4 at r2](https://reviewable.io:443/reviews/nowthisnews/http_eventstore/2#-KXFCFT6IzG0lfN9s2Th:-KXFCFT6IzG0lfN9s2Ti:b-as3i4v) ([raw file](https://github.com/nowthisnews/http_eventstore/blob/445a9c2678db6c31f08e24ca1c80e2446c820c37/lib/http_eventstore/api/client.rb#L4)):*
> ```Ruby
>   module Api
>     class Client
>       attr_reader :http_adapter
> ```

You can add this to att_reader used after initialize method

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/nowthisnews/http_eventstore/2)*

**Comment by rybex** [comment]
*[lib/http_eventstore/api/connection.rb, line 6 at r2](https://reviewable.io:443/reviews/nowthisnews/http_eventstore/2#-KXFCY0vOkP7tv3HXu2i:-KXFCY0vOkP7tv3HXu2j:bvb23jq) ([raw file](https://github.com/nowthisnews/http_eventstore/blob/445a9c2678db6c31f08e24ca1c80e2446c820c37/lib/http_eventstore/api/connection.rb#L6)):*
> ```Ruby
>       APP_JSON = 'application/json'.freeze
> 
>       attr_reader :http_adapter
> ```

The same here

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/nowthisnews/http_eventstore/2)*

**Comment by rybex** [comment]
:lgtm:

---

Reviewed 4 of 7 files at r1, 3 of 6 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/nowthisnews/http_eventstore/2#-:-KXFE7LQYxqVk4a7mXB8:bnfp4nl)*

**Comment by bilus** [comment]
:lgtm:

---

Reviewed 4 of 7 files at r1, 3 of 6 files at r2, 2 of 2 files at r3.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/nowthisnews/http_eventstore/2#-:-KXFFgwhn7GB7VpiuzHI:bnfp4nl)*

**Pull request merged**
